# conda env create --file environment.yml
#  gpufit??
name: NIST_tomo_experimental
channels:
  - astra-toolbox
  - conda-forge
dependencies:
  - python=3.9
  - astra-toolbox           # reconstructions
  - cupy                    # cuda - numpy wrappers
  - cudatoolkit=11.3        # have to specify version for my computer
  - astropy                 # for reading .fit files
  - ipympl                  
  - ipython                 # interactive command-line environment
  - ipywidgets              # interactive plots in jupyter
  - jupyterlab
  - matplotlib
  - napari                  # n-dimensional data viewer
  - notebook
  - numba                   # python function compiler
  - numpy   
  - pillow                  # Image reading and writing
  - pip
  - scikit-image
  - scipy
  - tqdm                    # progress bars
  - pip:
      - jupyterlab_vim      # this optional
