# conda env create --file environment.yml
name: NIST_tomo
channels:
  - astra-toolbox
  - conda-forge
dependencies:
  - python=3.7
  - astra-toolbox           # reconstructions
  - cupy                    # cuda - numpy wrappers
  - cudatoolkit=11.2        # have to specify version for my computer
  - astropy                 # for reading .fit files
  - ipympl                  
  - ipython                 # interactive command-line environment
  - ipywidgets              # interactive plots in jupyter
  - jupyter                 
  - jupyterlab
  - matplotlib
  - numba                   # python function compiler
  - numpy   
  - pillow                  # Image reading and writing
  - scikit-image
  - scipy
  - tqdm                    # progress bars
