COR:
  theta: 0.8203653092547202
  y0: 113
  y1: 2031
SARE:
  la_size: 45
  sm_size: 3
  snr: 3.0
crop:
  x0: 93
  x1: 2268
  y0: 425
  y1: 2002
name: __pens__unittest__
norm:
  x0: 226
  x1: 2427
  y0: 111
  y1: 384
paths:
  dark_path: D:/Data/Pens/dark
  flat_path: D:/Data/Pens/flat2
  projection_path: D:/Data/Pens/projections
post_processing:
  median kernel:
  - 3
  - 3
  - 3
pre_processing:
  angle_argument: 2
  dtype: float32
  extension: fit
  filename_delimiter: _
  median_xy: 3
  thresh median kernels:
  - 5
  - 7
  thresh median z-scores:
  - 1.0
  - 1.0
  transpose: true
recon:
  algorithm: FBP_CUDA
  geometry: parallel
  options:
    FilterType: hamming
    GPUindex: 0
  origin to detector distance: 0.0
  pixel pitch: 0.009
  reproduction ratio: 1.0
  source to origin distance: 0.0
